name: Example Workflow

on:
    workflow_dispatch:

jobs:
    unit_testing:
        runs-on: ubuntu-latest
        steps:
            - name: Get files
              uses: actions/checkout@v2
            - name: Say hello
              run: |
                echo "Hello"
                echo "How are you today?"
                pwd
                ls -la